"""Real-world exercise: an autonomous cloud-security agent governed by ICEBOX.

Mirrors the founder scenario. Uses real ICEBOX capabilities. The dangerous
action (privilege escalation / instance termination) is gated behind an
approval rule; the founder reviews and says NO. A tamper-evident audit trail
is produced for every decision.
"""

import json
import urllib.request

BASE = "http://127.0.0.1:8443"


def _post(path, body):
    req = urllib.request.Request(
        BASE + path, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"}, method="POST",
    )
    with urllib.request.urlopen(req, timeout=10) as r:
        return json.loads(r.read())


def setup():
    _post("/api/v1/charter", {"engagement": "acme-cloud-sec"})
    _post("/api/v1/scope", {"target": "10.0.0.0/8"})
    # Gate dangerous capabilities behind human approval.
    _post("/api/v1/policy/rules", {
        "require_approval": {
            "capability": "PrivilegeEscalation",
            "target_pattern": "*",
        }
    })


# A pretend autonomous agent. In reality these call AWS/Terraform APIs.
ACTIONS = [
    {"action": "scan_account", "target": "10.1.2.3", "capability": "NetworkScan",
     "impact": "low", "destructive": False, "note": "Enumerate the AWS account"},
    {"action": "check_iam", "target": "10.1.2.3", "capability": "CloudEnumeration",
     "impact": "low", "destructive": False, "note": "Review IAM permissions"},
    {"action": "vuln_scan", "target": "10.5.5.5", "capability": "NetworkScan",
     "impact": "medium", "destructive": False, "note": "Scan an instance for CVEs"},
    {"action": "terminate_ec2", "target": "10.9.9.9", "capability": "PrivilegeEscalation",
     "impact": "critical", "destructive": True, "note": "TERMINATE a production EC2 instance"},
    {"action": "suggest_fix", "target": "10.5.5.5", "capability": "Read",
     "impact": "low", "destructive": False, "note": "Suggest a remediation"},
]


def main():
    setup()
    print("Autonomous Cloud-Security Agent starting under ICEBOX governance.\n")
    for action in ACTIONS:
        print(f"Agent proposes: {action['note']} "
              f"(risk={action['impact']}, destructive={action['destructive']})")
        verdict = _post("/api/v1/govern", {
            "action": action["action"],
            "target": action["target"],
            "capability": action["capability"],
            "impact": action["impact"],
            "destructive": action["destructive"],
        })
        decision = verdict.get("decision")
        if verdict.get("approved"):
            print(f"    ICEBOX: APPROVED ({decision}) -> EXECUTED: {action['note']}")
            _post("/api/v1/govern/record", {
                "action": action, "outcome": {"success": True, "evidence": [f"ran {action['action']}"], "data": {}},
                "decision": decision,
            })
        elif decision == "require_approval":
            print(f"    ICEBOX: APPROVAL REQUIRED — reason: {verdict.get('reason')}")
            print("    Founder review: NO — do not execute.")
        else:
            print(f"    ICEBOX: BLOCKED ({decision}) — reason: {verdict.get('reason')}")
            print("    Founder review: NO — do not execute.")
        print()
    print("Agent finished. Audit trail generated by ICEBOX.\n")
    print("=== Audit trail (last 10 decisions) ===")
    req = urllib.request.Request(BASE + "/api/v1/audit?n=10")
    with urllib.request.urlopen(req) as r:
        for d in json.loads(r.read()):
            print(f"  [{d['at']}] {d['module']} -> {d['target']} : {d['decision']} (impact={d['impact']})")


if __name__ == "__main__":
    main()
